apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "communication-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "communication-server.name" . }}
    helm.sh/chart: {{ include "communication-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.enableRollingUpdate }}
  strategy:
    type: RollingUpdate
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "communication-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "communication-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        timestamp: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DB_HOST"
              value: {{ .Values.dbHost }}
            - name: "DB_NAME"
              value: {{ .Values.dbName }}
            - name: "DB_USER"
              value: {{ .Values.dbUser }}
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: communicationServerMongodbPassword
                  name: {{ .Release.Name }}-secrets
            {{- if .Values.enableEventStore }}
            - name: "ES_HOST"
              value: {{ .Values.eventStoreHost }}
            - name: "ES_STREAM"
              value: {{ .Values.eventStoreStream }}
            - name: "ES_USER"
              value: {{ .Values.eventStoreUser }}
            - name: "ES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: communicationServerEventStorePassword
                  name: {{ .Release.Name }}-secrets
            {{- end }}
            - name: "NODE_ENV"
              value: {{ .Values.NODE_ENV }}
          ports:
            - name: http
              containerPort: 4100
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /api/healthz
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /api/healthz
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
