apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  accountingServerRedisPassword: {{ .Values.redis.password }}
  accountingServerPostgresqlPassword: {{ index .Values "accounting-server" "postgresqlPassword" }}
  accountingServerMongodbPassword: {{ index .Values "accounting-server" "mongodbPassword" }}
  managementConsoleDbPassword: {{ index .Values "management-console" "dbPassword" }}
