apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-provider.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "identity-provider.name" . }}
    helm.sh/chart: {{ include "identity-provider.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.enableRollingUpdate }}
  strategy:
    type: RollingUpdate
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "identity-provider.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "identity-provider.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DB_HOST"
              value: {{ .Values.dbHost }}
            - name: "DB_NAME"
              value: {{ .Values.dbName }}
            - name: "DB_USER"
              value: {{ .Values.dbUser }}
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: identityProviderMongodbPassword
                  name: {{ .Release.Name }}-secrets
            {{- if .Values.enableEventStore }}
            - name: "ES_HOST"
              value: {{ .Values.eventStoreHost }}
            - name: "ES_STREAM"
              value: {{ .Values.eventStoreStream }}
            - name: "ES_USER"
              value: {{ .Values.eventStoreUser }}
            - name: "ES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: identityProviderEventStorePassword
                  name: {{ .Release.Name }}-secrets
            {{- end }}
            - name: "NODE_ENV"
              value: {{ .Values.NODE_ENV }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /api/healthz
              port: 3200
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /api/healthz
              port: 3200
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
