apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  eventStorePassword: {{ .Values.eventStorePassword | quote }}
  twilioSid: {{ .Values.twilioSid | quote }}
  twilioAuthToken: {{ .Values.twilioAuthToken | quote }}
  twilioNumber: {{ .Values.twilioNumber | quote }}
