apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  frappeConnectorDbPassword: {{ .Values.dbPassword }}
  frappeConnectorEventStorePassword: {{ .Values.eventStorePassword }}
