# Default values for quickbooks-blocks-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/castlecraft/quickbooks-blocks-connector/quickbooks-connector
  tag: latest
  pullPolicy: Always

frontendImage:
  repository: registry.gitlab.com/castlecraft/quickbooks-blocks-connector/quickbooks-connector-ui
  tag: latest
  pullPolicy: Always

NODE_ENV: production

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  paths:
    - /
  hosts:
    - qbcon.castlecraft.in
  tls:
    - secretName: qbcon-castlecraft-in-prod-tls
      hosts:
        - qbcon.castlecraft.in

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

enableRollingUpdate: false
initialDelaySeconds: 30
dbUsername: quickbooks-connector
dbDatabase: quickbooks-connector
dbPassword: admin
dbHost: "global-mongodb.mongodb.svc.cluster.local"
enableEventStore: false
eventStoreHost: "global-eventstore.eventstore.svc.cluster.local"
eventStoreStream: "$stg-qbc-cc-in"
eventStoreUser: "admin"
eventStorePassword: "changeit"
