{{- if .Values.enableSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  accountingServerRedisPassword: {{ .Values.redisPassword }}
  accountingServerPostgresqlPassword: {{ .Values.postgresqlPassword }}
  accountingServerMongodbPassword: {{ .Values.mongodbPassword }}
{{- end }}
