apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "infrastructure-console.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "infrastructure-console.name" . }}
    helm.sh/chart: {{ include "infrastructure-console.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "infrastructure-console.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "infrastructure-console.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DB_HOST"
              value: {{ .Values.dbHost }}
            - name: "DB_NAME"
              value: {{ .Values.dbName }}
            - name: "DB_USER"
              value: {{ .Values.dbUser }}
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  infrastructureConsoleMongodbPassword
                  name: {{ .Release.Name }}-secrets
            - name: "NODE_ENV"
              value: {{ .Values.NODE_ENV }}
          livenessProbe:
            httpGet:
              path: /info
              port: 5000
          readinessProbe:
            httpGet:
              path: /info
              port: 5000
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
