dependencies:
- name: redis
  version: 5.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: accounting-server
  repository: file://charts/accounting-server
- name: management-console
  repository: file://charts/management-console
- name: invoice-server
  repository: file://charts/invoice-server