apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  sessionSecret: {{ index .Values "authorization-server" "sessionSecret" }}
  authorizationServerMongodbPassword: {{ .Values.mongodb.authorizationServerMongodbPassword }}
  communicationServerMongodbPassword: {{ .Values.mongodb.communicationServerMongodbPassword }}
  identityProviderMongodbPassword: {{ .Values.mongodb.identityProviderMongodbPassword }}
  infrastructureConsoleMongodbPassword: {{ .Values.mongodb.infrastructureConsoleMongodbPassword }}
  bullQueueRedisPassword: {{ .Values.redis.password }}
