apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  sessionSecret: {{ index .Values "authorization-server" "sessionSecret" }}
  mongodbPassword: {{ .Values.mongodb.mongodbPassword }}
  mongodbRootPassword: {{ .Values.mongodb.mongodbRootPassword }}
  {{- if .Values.global.mongodumpCronJob.enabled }}
  storageAccessKey: {{ .Values.global.mongodumpCronJob.accessKey }}
  storageSecretKey: {{ .Values.global.mongodumpCronJob.secretKey }}
  {{- end }}
