apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  sessionSecret: {{ index .Values "authorization-server" "sessionSecret" }}
  authorizationServerMongodbPassword: {{ .Values.mongodb.authorizationServerMongodbPassword }}
  communicationServerMongodbPassword: {{ .Values.mongodb.communicationServerMongodbPassword }}
  identityProviderMongodbPassword: {{ .Values.mongodb.identityProviderMongodbPassword }}
  infrastructureConsoleMongodbPassword: {{ .Values.mongodb.infrastructureConsoleMongodbPassword }}
  {{- if index .Values "authorization-server" "enableEventStore" }}
  authorizationServerEventStorePassword: {{ .Values.eventStore.authorizationServerEventStorePassword }}
  {{- end }}
  {{- if index .Values "communication-server" "enableEventStore" }}
  communicationServerEventStorePassword: {{ .Values.eventStore.communicationServerEventStorePassword }}
  {{- end }}
  {{- if index .Values "identity-provider" "enableEventStore" }}
  identityProviderEventStorePassword: {{ .Values.eventStore.identityProviderEventStorePassword }}
  {{- end }}
  {{- if index .Values "infrastructure-console" "enableEventStore" }}
  infrastructureConsoleEventStorePassword: {{ .Values.eventStore.infrastructureConsoleEventStorePassword }}
  {{- end }}
