apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  sessionSecret: {{ .Values.sessionSecret }}
  mongodbPassword: {{ .Values.mongodb.mongodbPassword }}
  mongodbRootPassword: {{ .Values.mongodb.mongodbRootPassword }}
