apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "authorization-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "authorization-server.name" . }}
    helm.sh/chart: {{ include "authorization-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "authorization-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "authorization-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-authorization-server-data
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-authorization-server-data

      {{- else }}
          emptyDir: {}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name : {{ .Release.Name }}-authorization-server-data
              mountPath : "/home/craft/authorization-server/files"
          env:
            - name: "BULL_QUEUE_REDIS_HOST"
              value: {{ template "redis.fullname" . }}-master
            - name: "BULL_QUEUE_REDIS_PORT"
              value: "6379"
            - name: "SESSION_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  sessionSecret
                  name: {{ .Release.Name }}-authorization-server-secrets
            - name: "EXPIRY_DAYS"
              value: "1"
            - name: "COOKIE_MAX_AGE"
              value: "86400000"
            - name: "SESSION_NAME"
              value: "AS_SESSION"
            - name: "TOKEN_VALIDITY"
              value: "3600"
            - name: "DB_HOST"
              value: {{ template "mongodb.fullname" . }}
            - name: "DB_NAME"
              value: "authorization-server"
            - name: "DB_USER"
              value: "authorization-server"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  mongodbPassword
                  name: {{ .Release.Name }}-secrets
            - name: "MONGODB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  mongodbRootPassword
                  name: {{ .Release.Name }}-secrets
            - name: "NODE_ENV"
              value: {{ .Values.NODE_ENV }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /info
              port: http
          readinessProbe:
            httpGet:
              path: /info
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
