apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  quickbooksConnectorDbPassword: {{ .Values.dbPassword }}
  quickbooksConnectorEventStorePassword: {{ .Values.eventStorePassword }}
