dependencies:
- name: authorization-server
  repository: file://charts/authorization-server
- name: communication-server
  repository: file://charts/communication-server
- name: identity-provider
  repository: file://charts/identity-provider
- name: infrastructure-console
  repository: file://charts/infrastructure-console
