# Default values for building-blocks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

authorization-server:
  dbUser: "as-castlecraft-in"
  dbName: "as-castlecraft-in"
  sessionSecret: secret
  enableEventStore: true
  eventStoreStream: "$bb-staging"
  eventStoreUser: "admin"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
      - accounts.castlecraft.in
    tls:
      - secretName: accounts-castlecraft-in-tls
        hosts:
          - accounts.castlecraft.in

communication-server:
  dbUser: "cs-castlecraft-in"
  dbName: "cs-castlecraft-in"
  enableEventStore: true
  eventStoreStream: "$bb-staging"
  eventStoreUser: "admin"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
      - connect.castlecraft.in
    tls:
      - secretName: connect-castlecraft-in-tls
        hosts:
          - connect.castlecraft.in

identity-provider:
  dbUser: "idp-castlecraft-in"
  dbName: "idp-castlecraft-in"
  enableEventStore: true
  eventStoreStream: "$bb-staging"
  eventStoreUser: "admin"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
      - myaccount.castlecraft.in
    tls:
      - secretName: myaccount-castlecraft-in-tls
        hosts:
          - myaccount.castlecraft.in

infrastructure-console:
  dbUser: "ic-castlecraft-in"
  dbName: "ic-castlecraft-in"
  enableEventStore: true
  eventStoreStream: "$bb-staging"
  eventStoreUser: "admin"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
      - admin.castlecraft.in
    tls:
      - secretName: admin-castlecraft-in-tls
        hosts:
          - admin.castlecraft.in

mongodb:
  authorizationServerMongodbPassword: secret
  communicationServerMongodbPassword: secret
  identityProviderMongodbPassword: secret
  infrastructureConsoleMongodbPassword: secret

redis:
  usePassword: true
  password: secret
  networkPolicy:
    enabled: true
    allowExternal: true
  master:
    persistence:
      enabled: false
      size: 1Gi
      # storageClass: do-block-storage

eventStore:
  authorizationServerEventStorePassword: "changeit"
  communicationServerEventStorePassword: "changeit"
  identityProviderEventStorePassword: "changeit"
  infrastructureConsoleEventStorePassword: "changeit"
